version: "3.8"

services:
  # MySQL
  db:
    image: mysql:8.0
    container_name: kxo205_db
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: KXO205
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_HOST_AUTH_METHOD: mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - kxo205_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # PHP
  web:
    image: php:8.2-apache
    container_name: kxo205_web
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./includes/dbconn_docker.php:/var/www/html/includes/dbconn.php
      - ./:/var/www/html
    networks:
      - kxo205_network
    build:
      context: .
      dockerfile: Dockerfile

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kxo205_phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: "123456"
    networks:
      - kxo205_network

volumes:
  db_data:
    driver: local

networks:
  kxo205_network:
    driver: bridge
